# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.crypto import get_random_string
from authentication.models import Account


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160223_0036'),
    ]

    def gen_activation_keys(apps, schema_editor):
        for user in Account.objects.all():
            user.activate_key = get_random_string(64).lower()
            user.save()

    operations = [
        migrations.AddField(
            model_name='account',
            name='activate_key',
            field=models.CharField(default='', max_length=64, verbose_name='Activate key'),
            preserve_default=False,
        ),
        migrations.RunPython(gen_activation_keys),
        migrations.AlterField(
            model_name='account',
            name='activate_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='Activate key'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
