# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160317_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Department name')),
                ('can_use_in_procentage', models.PositiveIntegerField(default=100, help_text='Example: You set 50%. To this department assignet subscription with 1000 licenses and this department can use only 50% of 1000 licenses', verbose_name='Can use a subscription no more then %')),
                ('can_use_in_currency', models.PositiveIntegerField(default=10000, help_text='Example: You set 10$. To this department assignet subscription with 100$ price and this department can use only licenses at a price no higher than 10$', verbose_name='Can use a subscription no more then $')),
                ('can_use_in_licenses', models.PositiveIntegerField(default=10000, help_text='Example: You set 100 licenses. To this department assignet subscription with 1000 licenses and this department can use only 100 licenses', verbose_name='Can use a subscription no more then X licenses')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
