# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(related_name='department', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
