# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160317_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='department', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
