# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20160317_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Company Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='Departments', to='authentication.Department'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
