# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160322_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activate_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Activate key'),
        ),
        migrations.AlterField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='company', to='authentication.Department', verbose_name='Departments'),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
