# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20160322_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='can_use_in_currency',
        ),
    ]
