# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20160322_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Contact phone number'),
        ),
    ]
