# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to=b'invoice', verbose_name='Invoice')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('created_dt', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.DateField(auto_now_add=True, verbose_name='Expired date')),
                ('licenses', models.PositiveIntegerField(verbose_name='Purchased licenses')),
                ('assigned', models.PositiveIntegerField(default=0, verbose_name='Assigned licenses')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('created_dt', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice', verbose_name='Invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
