# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 18:14
from __future__ import unicode_literals

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20160315_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired',
            field=models.DateField(default=billing.models.get_expired, verbose_name='Expired date'),
        ),
    ]
