# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscription_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=-4, max_length=255, verbose_name='Invoice number'),
            preserve_default=False,
        ),
    ]
