# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_department'),
        ('billing', '0008_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='departments',
            field=models.ManyToManyField(to='authentication.Department', verbose_name='Departments'),
        ),
    ]
