# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_subscription_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='users',
        ),
    ]
