# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20160317_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='departments',
            field=models.ManyToManyField(blank=True, to='authentication.Department', verbose_name='Departments'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='billing.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
