# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20160317_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended subscription'),
        ),
    ]
