# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20160322_0411'),
        ('billing', '0012_subscription_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
