# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscription_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='users',
        ),
    ]
