# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_department_can_use_in_currency'),
        ('billing', '0014_remove_subscription_users'),
    ]

    def gen_fake_company(apps, schema_editor):
        from authentication.models import Company
        if Company.objects.count() == 0:
            Company(name='Fake').save()

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RunPython(gen_fake_company),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
