# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='eg. John', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(help_text='eg. Smith', max_length=30, verbose_name='last name')),
                ('email', models.EmailField(help_text='eg. John@xyz.com', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='eg. +1 (123) 456-789', max_length=100, verbose_name='Phone number')),
                ('job_title', models.CharField(blank=True, help_text='eg. Engineer', max_length=100, verbose_name='Job Title')),
                ('need_furniture', models.BooleanField(default=False, verbose_name='Need furniture package for this employee?')),
                ('duration', models.PositiveIntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (1, '1 Year or longer')], default=3, verbose_name='How long will this employee stay?')),
                ('is_reusable', models.BooleanField(verbose_name='Is reusable employee?')),
                ('is_requested_stage', models.BooleanField(verbose_name='Is employee in requested stage?')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRelocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relocate_from', models.CharField(max_length=200, verbose_name='Relocating from')),
                ('relocate_to', models.CharField(max_length=200, verbose_name='Relocating to')),
                ('expected_moving_date', models.DateField(verbose_name='Expected moving date')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Received'), (2, 'Confirmed'), (3, 'Cancelled')], default=1, verbose_name='Employee status')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(to='employee.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
