# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_requested_stage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='need_furniture',
        ),
        migrations.AddField(
            model_name='employeerelocation',
            name='duration',
            field=models.PositiveIntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (1, '1 Year or longer')], default=3, verbose_name='How long will this employee stay?'),
        ),
        migrations.AddField(
            model_name='employeerelocation',
            name='need_furniture',
            field=models.BooleanField(default=False, verbose_name='Need furniture package for this employee?'),
        ),
    ]
