# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20160223_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerelocation',
            name='updated_dt',
            field=models.DateTimeField(null=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='employeerelocation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='employeerelocation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Initial'), (1, 'Received'), (2, 'Confirmed'), (3, 'Cancelled')], default=0, verbose_name='Employee status'),
        ),
    ]
