# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20160223_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_reusable',
            field=models.BooleanField(default=True, verbose_name='Is reusable employee?'),
        ),
    ]
