# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20160224_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerelocation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update date'),
        ),
    ]
