# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20160301_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerelocation',
            name='special_needs',
            field=models.TextField(blank=True, verbose_name='Special needs'),
        ),
    ]
