# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeerelocation_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerelocation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Initial'), (1, 'Received'), (2, 'In process'), (3, 'Confirmed'), (4, 'Successful'), (5, 'Cancelled')], default=0, verbose_name='Employee status'),
        ),
    ]
