# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20160327_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='activated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activated date on main site'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activated on main site'),
        ),
    ]
