# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_created_on_main_site',
            field=models.BooleanField(default=False, verbose_name='Is created on the main site?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_reusable',
            field=models.BooleanField(default=False, verbose_name='Is reusable employee?'),
        ),
        migrations.AlterField(
            model_name='employeerelocation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Initial'), (1, 'Received'), (2, 'In process'), (4, 'Successful'), (5, 'Cancelled')], default=0, verbose_name='Employee status'),
        ),
    ]
