# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_logging', '0002_auto_20160314_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Request IP'),
            preserve_default=False,
        ),
    ]
