# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_logging', '0003_log_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.CharField(max_length=500, verbose_name='Event'),
        ),
    ]
