# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db_logging', '0004_auto_20160314_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='object',
        ),
        migrations.AddField(
            model_name='log',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='log',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
            preserve_default=False,
        ),
    ]
